<?php
use Kafoso\Tools\Generic\HTML;

$classes = ["options"];
if ($this->configuration->areOptionsShown()) {
    $classes[] = "isShown";
}
$classes = implode(" ", $classes);

$truncatedGenericClasses = array_map(function($className){
    return '\\' . $className;
}, $this->truncatedGenericClasses);
$textTruncatedGenericClasses = ", and " . array_pop($truncatedGenericClasses);
$textTruncatedGenericClasses = implode(", ", $truncatedGenericClasses) . $textTruncatedGenericClasses;
?>
<div class="<?=$classes?>">
    <div class="option">
        <div class="label">Collapse level:</div>
        <div class="value">
            <input type="number" placeholder="2" data-option="collapseLevel" style="width:60px;" value="<?=HTML::encode($this->configuration->getCollapseLevel())?>">
        </div>
    </div>
    <div class="option">
        <div class="label">Show parent class:</div>
        <div class="value">
            <select data-option="isShowingParentClass" class="reaction <?=($this->configuration->isShowingParentClass() ? "positive" : "negative")?>">
                <option value="1" <?=($this->configuration->isShowingParentClass() ? "selected" : "")?>>Yes</option>
                <option value="0" <?=(false == $this->configuration->isShowingParentClass() ? "selected" : "")?>>No</option>
            </select>
        </div>
    </div>
    <div class="option">
        <div class="label">Show implemented interfaces:</div>
        <div class="value">
            <select data-option="isShowingInterfaces" class="reaction <?=($this->configuration->isShowingInterfaces() ? "positive" : "negative")?>">
                <option value="1" <?=($this->configuration->isShowingInterfaces() ? "selected" : "")?>>Yes</option>
                <option value="0" <?=(false == $this->configuration->isShowingInterfaces() ? "selected" : "")?>>No</option>
            </select>
        </div>
    </div>
    <div class="option">
        <div class="label">Show traits:</div>
        <div class="value">
            <select data-option="isShowingTraits" class="reaction <?=($this->configuration->isShowingTraits() ? "positive" : "negative")?>">
                <option value="1" <?=($this->configuration->isShowingTraits() ? "selected" : "")?>>Yes</option>
                <option value="0" <?=(false == $this->configuration->isShowingTraits() ? "selected" : "")?>>No</option>
            </select>
        </div>
    </div>
    <div class="option">
        <div class="label">Show constants:</div>
        <div class="value">
            <select data-option="isShowingConstants" class="reaction <?=($this->configuration->isShowingConstants() ? "positive" : "negative")?>">
                <option value="1" <?=($this->configuration->isShowingConstants() ? "selected" : "")?>>Yes</option>
                <option value="0" <?=(false == $this->configuration->isShowingConstants() ? "selected" : "")?>>No</option>
            </select>
        </div>
    </div>
    <div class="option">
        <div class="label">Show class variables:</div>
        <div class="value">
            <select data-option="isShowingVariables" class="reaction <?=($this->configuration->isShowingVariables() ? "positive" : "negative")?>">
                <option value="1" <?=($this->configuration->isShowingVariables() ? "selected" : "")?>>Yes</option>
                <option value="0" <?=(false == $this->configuration->isShowingVariables() ? "selected" : "")?>>No</option>
            </select>
        </div>
    </div>
    <div class="option">
        <div class="label">Show methods:</div>
        <div class="value">
            <select data-option="isShowingMethods" class="reaction <?=($this->configuration->isShowingMethods() ? "positive" : "negative")?>">
                <option value="1" <?=($this->configuration->isShowingMethods() ? "selected" : "")?>>Yes</option>
                <option value="0" <?=(false == $this->configuration->isShowingMethods() ? "selected" : "")?>>No</option>
            </select>
        </div>
    </div>
    <div class="option">
        <div class="label">Show method parameters:</div>
        <div class="value">
            <select data-option="isShowingMethodParameters" class="reaction <?=($this->configuration->isShowingMethodParameters() ? "positive" : "negative")?>">
                <option value="1" <?=($this->configuration->isShowingMethodParameters() ? "selected" : "")?>>Yes</option>
                <option value="0" <?=(false == $this->configuration->isShowingMethodParameters() ? "selected" : "")?>>No</option>
            </select>
        </div>
    </div>
    <div class="option">
        <div class="label">Show method type hints (<span class="hint" title="Type hints include: array, boolean, callable, \Closure, float, integer, null, string, and any object."><span class="syntax--support syntax--class">string</span>, <span class="syntax--support syntax--class">int</span>, etc.</span>):</div>
        <div class="value">
            <select data-option="isShowingMethodParameterTypeHints" class="reaction <?=($this->configuration->isShowingMethodParameterTypeHints() ? "positive" : "negative")?>">
                <option value="1" <?=($this->configuration->isShowingMethodParameterTypeHints() ? "selected" : "")?>>Yes</option>
                <option value="0" <?=(false == $this->configuration->isShowingMethodParameterTypeHints() ? "selected" : "")?>>No</option>
            </select>
        </div>
    </div>
    <div class="option">
        <div class="label">Truncate generic objects (<span class="hint" title="<?=HTML::encode("Objects being truncated are: {$textTruncatedGenericClasses}.")?>">like <span class="syntax--entity syntax--name syntax--class">\DateTime</span></span>):</div>
        <div class="value">
            <select data-option="isTruncatingGenericObjects" class="reaction <?=($this->configuration->isTruncatingGenericObjects() ? "positive" : "negative")?>">
                <option value="1" <?=($this->configuration->isTruncatingGenericObjects() ? "selected" : "")?>>Yes</option>
                <option value="0" <?=(false == $this->configuration->isTruncatingGenericObjects() ? "selected" : "")?>>No</option>
            </select>
            <span class="text-muted">This operation is performed server-side. Requires reload.</span>
        </div>
    </div>
</div>
