<?php
use Kafoso\Tools\Generic\HTML;

$outputClasses = ["output"];
if (false == $this->configuration->isShowingParentClass()) {
    $outputClasses[] = "isHidingParentClass";
}
if (false == $this->configuration->isShowingInterfaces()) {
    $outputClasses[] = "isHidingInterfaces";
}
if (false == $this->configuration->isShowingTraits()) {
    $outputClasses[] = "isHidingTraits";
}
if (false == $this->configuration->isShowingConstants()) {
    $outputClasses[] = "isHidingConstants";
}
if (false == $this->configuration->isShowingVariables()) {
    $outputClasses[] = "isHidingVariables";
}
if (false == $this->configuration->isShowingMethods()) {
    $outputClasses[] = "isHidingMethods";
}
if (false == $this->configuration->isShowingMethodParameters()) {
    $outputClasses[] = "isHidingMethodParameters";
}
if (false == $this->configuration->isShowingMethodParameterTypeHints()) {
    $outputClasses[] = "isHidingMethodParameters";
}
$outputClasses = implode(" ", $outputClasses);
?>
<div class="Kafoso_Tools_Debug_Dumper" id="<?=HTML::encode($this->uuid)?>">
    <style type="text/css"><?=$this->css?></style>
    <div class="optionsButton" title="Click to toggle options menu."></div>
    <?=$this->render("Kafoso/Tools/Debug/Dumper/HtmlFormatter/render/origin.phtml")?>
    <?=$this->render("Kafoso/Tools/Debug/Dumper/HtmlFormatter/render/options.phtml")?>
    <div class="<?=$outputClasses?>"><pre><div style="position:relative;z-index:2;"><?=$this->innerHtml?></div><div class="wrap-guide"><?=str_repeat(" ", $this->PSR_2_SOFT_CHARACTER_LIMIT)?></div></pre></div>
    <?=$this->render("Kafoso/Tools/Debug/Dumper/HtmlFormatter/render/javascript.phtml")?>
</div>
